apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::252333641297:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-40n8lXEYKoYh\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::252333641297:role/minhtq25_codebuild\n  username:
    build      \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-28T02:49:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3248"
  uid: 56679afa-e66f-4709-b0ef-88bb9125fa7d
